import { Competition, Player, Coach, Organizer, Referee } from './types';

export const BASELINE_GLOBAL_CLUBS: string[] = [
  "12345",
  "A Taekwondo HQ",
  "Acme Taekwondo",
  "ELITE TAEKWONDO SRI LANKA",
  "GK Taekwondo Pte Ltd",
  "Gk Taekwondo",
  "Han-Lim Taekwondo",
  "Induk Taekwondo",
  "KORYO TAEKWONDO CLUB",
  "MATSA TAEKWONDO CLUB",
  "Odan Taekwondo Team",
  "PUSAT SENI MEMPERTAHANKAN DIRI TAEKWONDO ACTION WTF",
  "Persatuan Taekwondo Negeri Kedah",
  "Primajaya tkd club",
  "SAUJANA TKD CLUB",
  "SMART MA TAEKWONDO CLUB",
  "TYC TAEKWONDO CLUB",
  "Taekwondo Negeri Pulau Pinang (WTF) (TNPP)",
  "Taekwondonomics Pte Ltd",
  "VERITAS TAEKWONDO INTERNATIONAL",
  "Woshin Taekwondo/Singapore"
];

export const BASELINE_COMPETITIONS: Competition[] = [
  {
    "endDate": "2026-09-05",
    "date": "2026-09-05",
    "name": "SMART MA CLOSE CHAMPIONSHIP 2026",
    "staffCode": "1",
    "events": [
      "Kyorugi",
      "Para Kyorugi",
      "Recognize Poomsae",
      "Free Style Poomsae",
      "Para Poomsae",
      "Virtual Taekwondo",
      "Kyukpa",
      "Speed Kicking",
      "Skipping Rope",
      "Recognize Poomsae 2"
    ],
    "isActive": false,
    "genders": [
      "Male",
      "Female",
      "Mix"
    ],
    "registrationCloseDate": "2026-09-01",
    "id": "smartmaclosecham7z9a",
    "venue": "MULTI PURPOSE HALL UNITAR SUNGAI LONG",
    "ageGroups": [],
    "weightClasses": []
  },
  {
    "genders": [
      "Male",
      "Female",
      "Mix"
    ],
    "id": "stteresacup2026udkr",
    "paraFee": "",
    "kyukpaFee": "80",
    "ageGroups": [
      "U6- 6 years old and below",
      "U8- 7 years old to 8 years old",
      "U10-9 years old to 10 years old",
      "U12-11 years old to 12 years old",
      "U14-13 years old to 14 years old",
      "U16-15 years old to 16 years old",
      "U19-17 years old to 19 years old",
      "U29-20 years old to 29 years old",
      "O30-30 years old and above"
    ],
    "skippingRopeFee": "80",
    "registrationCloseDate": "2026-10-16",
    "isActive": true,
    "staffCode": "sttc1",
    "packageFiveEventFee": "150",
    "packageSecondEventFee": "40",
    "endDate": "2026-11-14",
    "currency": "S$",
    "bankName": "OCBC",
    "eventWeightClasses": {
      "Free Style Poomsae": [],
      "Speed Kicking": [
        "SPEED KICKING, U6 & U8 & U10",
        "SPEED KICKING, U12 & U14",
        "SPEED KICKING, U16 & U19",
        "SPEED KICKING, U29 & O30"
      ],
      "Virtual Taekwondo": [],
      "Skipping Rope": [
        "30-second single bounce jump",
        "30-second reverse single bounce jump",
        "1-minute single bounce jump",
        "1-minute one-handle one-bounce jump"
      ],
      "Para Poomsae": [],
      "Para Kyorugi": [],
      "Recognize Poomsae 2": [
        "POOMSAE,Yellow 8 Taeguek 1",
        "POOMSAE,Yellow 7 Taeguek 2",
        "POOMSAE,Green 6 Taeguek 3",
        "POOMSAE,Green 5 Taeguek 4",
        "POOMSAE,Blue 4 Taeguek 5",
        "POOMSAE,Red 2 Taeguek 7",
        "POOMSAE,Red 1 Taeguek 8",
        "POOMSAE,Poom ,Koryo, Keumgang, Taebaek, Pyongwon,Sipjin",
        "POOMSAE,Dan, Koryo, Keumgang, Taebaek, Pyongwon,Sipjin"
      ],
      "Recognize Poomsae": [
        "POOMSAE,Yellow 8 Taeguek 1",
        "POOMSAE,Yellow 7 Taeguek 2",
        "POOMSAE,Green 5 Taeguek 4",
        "POOMSAE,Blue 4 Taeguek 5",
        "POOMSAE,Blue 3 Taeguek 6",
        "POOMSAE,Red 2 Taeguek 7",
        "POOMSAE,Red 1 Taeguek 8",
        "POOMSAE,Poom ,Koryo, Keumgang, Taebaek, Pyongwon,Sipjin",
        "POOMSAE,Dan, Koryo, Keumgang, Taebaek, Pyongwon,Sipjin",
        "POOMSAE,Green 6 Taeguek 3"
      ],
      "Kyorugi": [
        "KYORUGI,Male,U6,-20kg",
        "KYORUGI,Male,U6,-22kg",
        "KYORUGI,Male,U6,-24kg",
        "KYORUGI,Male,U6,-26kg",
        "KYORUGI,Male,U6,-28kg",
        "KYORUGI,Male,U6,-31kg",
        "KYORUGI,Male,U6,-34kg",
        "KYORUGI,Male,U6,-37kg",
        "KYORUGI,Male,U6,-40kg",
        "KYORUGI,Male,U6,-45kg",
        "KYORUGI,Female,U6,-17kg",
        "KYORUGI,Female,U6,-19kg",
        "KYORUGI,Female,U6,-21kg",
        "KYORUGI,Female,U6,-23kg",
        "KYORUGI,Female,U6,-25kg",
        "KYORUGI,Female,U6,-28kg",
        "KYORUGI,Female,U6,-31kg",
        "KYORUGI,Female,U6,-34kg",
        "KYORUGI,Female,U6,-38kg",
        "KYORUGI,Female,U6,-43kg",
        "KYORUGI,Male,U8,-24kg",
        "KYORUGI,Male,U8,-26kg",
        "KYORUGI,Male,U8,-29kg",
        "KYORUGI,Male,U8,-32kg",
        "KYORUGI,Male,U8,-36kg",
        "KYORUGI,Male,U8,-40kg",
        "KYORUGI,Male,U8,-44kg",
        "KYORUGI,Male,U8,-48kg",
        "KYORUGI,Male,U8,-53kg",
        "KYORUGI,Male,U8,-58kg",
        "KYORUGI,Female,U8,-22kg",
        "KYORUGI,Female,U8,-24kg",
        "KYORUGI,Female,U8,-26kg",
        "KYORUGI,Female,U8,-28kg",
        "KYORUGI,Female,U8,-31kg",
        "KYORUGI,Female,U8,-34kg",
        "KYORUGI,Female,U8,-38kg",
        "KYORUGI,Female,U8,-42kg",
        "KYORUGI,Female,U8,-46kg",
        "KYORUGI,Female,U8,-51kg",
        "KYORUGI,Male,U10,-26kg",
        "KYORUGI,Male,U10,-29kg",
        "KYORUGI,Male,U10,-32kg",
        "KYORUGI,Male,U10,-35kg",
        "KYORUGI,Male,U10,-38kg",
        "KYORUGI,Male,U10,-42kg",
        "KYORUGI,Male,U10,-46kg",
        "KYORUGI,Male,U10,-50kg",
        "KYORUGI,Male,U10,-55kg",
        "KYORUGI,Male,U10,-60kg",
        "KYORUGI,Female,U10,-24kg",
        "KYORUGI,Female,U10,-26kg",
        "KYORUGI,Female,U10,-28kg",
        "KYORUGI,Female,U10,-31kg",
        "KYORUGI,Female,U10,-34kg",
        "KYORUGI,Female,U10,-37kg",
        "KYORUGI,Female,U10,-41kg",
        "KYORUGI,Female,U10,-45kg",
        "KYORUGI,Female,U10,-49kg",
        "KYORUGI,Female,U10,-54kg",
        "KYORUGI,Male,U12,-26kg",
        "KYORUGI,Male,U12,-29kg",
        "KYORUGI,Male,U12,-32kg",
        "KYORUGI,Male,U12,-35kg",
        "KYORUGI,Male,U12,-38kg",
        "KYORUGI,Male,U12,-42kg",
        "KYORUGI,Male,U12,-46kg",
        "KYORUGI,Male,U12,-50kg",
        "KYORUGI,Male,U12,-55kg",
        "KYORUGI,Male,U12,-60kg",
        "KYORUGI,Female,U12,-24kg",
        "KYORUGI,Female,U12,-26kg",
        "KYORUGI,Female,U12,-28kg",
        "KYORUGI,Female,U12,-31kg",
        "KYORUGI,Female,U12,-34kg",
        "KYORUGI,Female,U12,-37kg",
        "KYORUGI,Female,U12,-41kg",
        "KYORUGI,Female,U12,-45kg",
        "KYORUGI,Female,U12,-49kg",
        "KYORUGI,Female,U12,-54kg",
        "KYORUGI,Male,U14,-33kg",
        "KYORUGI,Male,U14,-37kg",
        "KYORUGI,Male,U14,-41kg",
        "KYORUGI,Male,U14,-45kg",
        "KYORUGI,Male,U14,-49kg",
        "KYORUGI,Male,U14,-53kg",
        "KYORUGI,Male,U14,-57kg",
        "KYORUGI,Male,U14,-61kg",
        "KYORUGI,Male,U14,-65kg",
        "KYORUGI,Male,U14,-71kg",
        "KYORUGI,Female,U14,-29kg",
        "KYORUGI,Female,U14,-33kg",
        "KYORUGI,Female,U14,-37kg",
        "KYORUGI,Female,U14,-41kg",
        "KYORUGI,Female,U14,-44kg",
        "KYORUGI,Female,U14,-47kg",
        "KYORUGI,Female,U14,-51kg",
        "KYORUGI,Female,U14,-55kg",
        "KYORUGI,Female,U14,-59kg",
        "KYORUGI,Female,U14,-64kg",
        "KYORUGI,Male,U16,-36kg",
        "KYORUGI,Male,U16,-40kg",
        "KYORUGI,Male,U16,-44kg",
        "KYORUGI,Male,U16,-48kg",
        "KYORUGI,Male,U16,-52kg",
        "KYORUGI,Male,U16,-56kg",
        "KYORUGI,Male,U16,-60kg",
        "KYORUGI,Male,U16,-65kg",
        "KYORUGI,Male,U16,-70kg",
        "KYORUGI,Male,U16,-75kg",
        "KYORUGI,Female,U16,31kg",
        "KYORUGI,Female,U16,-34kg",
        "KYORUGI,Female,U16,-37kg",
        "KYORUGI,Female,U16,-41kg",
        "KYORUGI,Female,U16,-45kg",
        "KYORUGI,Female,U16,-49kg",
        "KYORUGI,Female,U16,-54kg",
        "KYORUGI,Female,U16,-59kg",
        "KYORUGI,Female,U16,-64kg",
        "KYORUGI,Female,U16,-69kg",
        "KYORUGI,Male,U19,-45kg",
        "KYORUGI,Male,U19,-48kg",
        "KYORUGI,Male,U19,-52kg",
        "KYORUGI,Male,U19,-56kg",
        "KYORUGI,Male,U19,60kg",
        "KYORUGI,Male,U19,-65kg",
        "KYORUGI,Male,U19,-71kg",
        "KYORUGI,Male,U19,-77kg",
        "KYORUGI,Male,U19,-85kg",
        "KYORUGI,Male,U19,-95kg",
        "KYORUGI,Female,U19,-42kg",
        "KYORUGI,Female,U19,-44kg",
        "KYORUGI,Female,U19,-46kg",
        "KYORUGI,Female,U19,-49kg",
        "KYORUGI,Female,U19,-54kg",
        "KYORUGI,Female,U19,-59kg",
        "KYORUGI,Female,U19,-64kg",
        "KYORUGI,Female,U19,-69kg",
        "KYORUGI,Female,U19,-75kg",
        "KYORUGI,Female,U19,-85kg",
        "KYORUGI,Male,U29,-45kg",
        "KYORUGI,Male,U29,-48kg",
        "KYORUGI,Male,U29,-52kg",
        "KYORUGI,Male,U29,-56kg",
        "KYORUGI,Male,U29,60kg",
        "KYORUGI,Male,U29,-65kg",
        "KYORUGI,Male,U29,-71kg",
        "KYORUGI,Male,U29,-77kg",
        "KYORUGI,Male,U29,-85kg",
        "KYORUGI,Male,U29,-95kg",
        "KYORUGI,Female,U29,-42kg",
        "KYORUGI,Female,U29,-44kg",
        "KYORUGI,Female,U29,-46kg",
        "KYORUGI,Female,U29,-49kg",
        "KYORUGI,Female,U29,-54kg",
        "KYORUGI,Female,U29,-59kg",
        "KYORUGI,Female,U29,-64kg",
        "KYORUGI,Female,U29,-69kg",
        "KYORUGI,Female,U29,-75kg",
        "KYORUGI,Female,U29,-85kg"
      ],
      "Kyukpa": [
        "KYUPKA, U6 & U8 & U10",
        "KYUPKA, U12 & U14",
        "KYUPKA, U16 & U19",
        "KYUPKA, U29 & O30"
      ]
    },
    "affiliatedClubs": [
      "GK Taekwondo Pte Ltd",
      "VERITAS TAEKWONDO INTERNATIONAL",
      "12345",
      "A Taekwondo HQ",
      "Acme Taekwondo",
      "ELITE TAEKWONDO SRI LANKA",
      "Gk Taekwondo",
      "Han-Lim Taekwondo",
      "Induk Taekwondo",
      "KORYO TAEKWONDO CLUB",
      "MATSA TAEKWONDO CLUB",
      "Odan Taekwondo Team",
      "PUSAT SENI MEMPERTAHANKAN DIRI TAEKWONDO ACTION WTF",
      "Persatuan Taekwondo Negeri Kedah",
      "Primajaya tkd club",
      "SAUJANA TKD CLUB",
      "SMART MA TAEKWONDO CLUB",
      "TYC TAEKWONDO CLUB",
      "Taekwondo Negeri Pulau Pinang (WTF) (TNPP)",
      "Taekwondonomics Pte Ltd",
      "Woshin Taekwondo/Singapore"
    ],
    "speedKickingFee": "80",
    "date": "2026-11-14",
    "venue": "SAFRA Choa Chu Kang, Activity Area. 28 Choa Chu Kang Drive Singapore 689964",
    "feeModel": "SPECIAL_PACKAGE",
    "packageFirstEventFee": "80",
    "weightClasses": [
      "KYORUGI,Male,U6,-20kg",
      "KYORUGI,Male,U6,-22kg",
      "KYORUGI,Male,U6,-24kg",
      "KYORUGI,Male,U6,-26kg",
      "KYORUGI,Male,U6,-28kg",
      "KYORUGI,Male,U6,-31kg",
      "KYORUGI,Male,U6,-34kg",
      "KYORUGI,Male,U6,-37kg",
      "KYORUGI,Male,U6,-40kg",
      "KYORUGI,Male,U6,-45kg",
      "KYORUGI,Female,U6,-17kg",
      "KYORUGI,Female,U6,-19kg",
      "KYORUGI,Female,U6,-21kg",
      "KYORUGI,Female,U6,-23kg",
      "KYORUGI,Female,U6,-25kg",
      "KYORUGI,Female,U6,-28kg",
      "KYORUGI,Female,U6,-31kg",
      "KYORUGI,Female,U6,-34kg",
      "KYORUGI,Female,U6,-38kg",
      "KYORUGI,Female,U6,-43kg",
      "KYORUGI,Male,U8,-24kg",
      "KYORUGI,Male,U8,-26kg",
      "KYORUGI,Male,U8,-29kg",
      "KYORUGI,Male,U8,-32kg",
      "KYORUGI,Male,U8,-36kg",
      "KYORUGI,Male,U8,-40kg",
      "KYORUGI,Male,U8,-44kg",
      "KYORUGI,Male,U8,-48kg",
      "KYORUGI,Male,U8,-53kg",
      "KYORUGI,Male,U8,-58kg",
      "KYORUGI,Female,U8,-22kg",
      "KYORUGI,Female,U8,-24kg",
      "KYORUGI,Female,U8,-26kg",
      "KYORUGI,Female,U8,-28kg",
      "KYORUGI,Female,U8,-31kg",
      "KYORUGI,Female,U8,-34kg",
      "KYORUGI,Female,U8,-38kg",
      "KYORUGI,Female,U8,-42kg",
      "KYORUGI,Female,U8,-46kg",
      "KYORUGI,Female,U8,-51kg",
      "KYORUGI,Male,U10,-26kg",
      "KYORUGI,Male,U10,-29kg",
      "KYORUGI,Male,U10,-32kg",
      "KYORUGI,Male,U10,-35kg",
      "KYORUGI,Male,U10,-38kg",
      "KYORUGI,Male,U10,-42kg",
      "KYORUGI,Male,U10,-46kg",
      "KYORUGI,Male,U10,-50kg",
      "KYORUGI,Male,U10,-55kg",
      "KYORUGI,Male,U10,-60kg",
      "KYORUGI,Female,U10,-24kg",
      "KYORUGI,Female,U10,-26kg",
      "KYORUGI,Female,U10,-28kg",
      "KYORUGI,Female,U10,-31kg",
      "KYORUGI,Female,U10,-34kg",
      "KYORUGI,Female,U10,-37kg",
      "KYORUGI,Female,U10,-41kg",
      "KYORUGI,Female,U10,-45kg",
      "KYORUGI,Female,U10,-49kg",
      "KYORUGI,Female,U10,-54kg",
      "KYORUGI,Male,U12,-26kg",
      "KYORUGI,Male,U12,-29kg",
      "KYORUGI,Male,U12,-32kg",
      "KYORUGI,Male,U12,-35kg",
      "KYORUGI,Male,U12,-38kg",
      "KYORUGI,Male,U12,-42kg",
      "KYORUGI,Male,U12,-46kg",
      "KYORUGI,Male,U12,-50kg",
      "KYORUGI,Male,U12,-55kg",
      "KYORUGI,Male,U12,-60kg",
      "KYORUGI,Female,U12,-24kg",
      "KYORUGI,Female,U12,-26kg",
      "KYORUGI,Female,U12,-28kg",
      "KYORUGI,Female,U12,-31kg",
      "KYORUGI,Female,U12,-34kg",
      "KYORUGI,Female,U12,-37kg",
      "KYORUGI,Female,U12,-41kg",
      "KYORUGI,Female,U12,-45kg",
      "KYORUGI,Female,U12,-49kg",
      "KYORUGI,Female,U12,-54kg",
      "KYORUGI,Male,U14,-33kg",
      "KYORUGI,Male,U14,-37kg",
      "KYORUGI,Male,U14,-41kg",
      "KYORUGI,Male,U14,-45kg",
      "KYORUGI,Male,U14,-49kg",
      "KYORUGI,Male,U14,-53kg",
      "KYORUGI,Male,U14,-57kg",
      "KYORUGI,Male,U14,-61kg",
      "KYORUGI,Male,U14,-65kg",
      "KYORUGI,Male,U14,-71kg",
      "KYORUGI,Female,U14,-29kg",
      "KYORUGI,Female,U14,-33kg",
      "KYORUGI,Female,U14,-37kg",
      "KYORUGI,Female,U14,-41kg",
      "KYORUGI,Female,U14,-44kg",
      "KYORUGI,Female,U14,-47kg",
      "KYORUGI,Female,U14,-51kg",
      "KYORUGI,Female,U14,-55kg",
      "KYORUGI,Female,U14,-59kg",
      "KYORUGI,Female,U14,-64kg",
      "KYORUGI,Male,U16,-36kg",
      "KYORUGI,Male,U16,-40kg",
      "KYORUGI,Male,U16,-44kg",
      "KYORUGI,Male,U16,-48kg",
      "KYORUGI,Male,U16,-52kg",
      "KYORUGI,Male,U16,-56kg",
      "KYORUGI,Male,U16,-60kg",
      "KYORUGI,Male,U16,-65kg",
      "KYORUGI,Male,U16,-70kg",
      "KYORUGI,Male,U16,-75kg",
      "KYORUGI,Female,U16,31kg",
      "KYORUGI,Female,U16,-34kg",
      "KYORUGI,Female,U16,-37kg",
      "KYORUGI,Female,U16,-41kg",
      "KYORUGI,Female,U16,-45kg",
      "KYORUGI,Female,U16,-49kg",
      "KYORUGI,Female,U16,-54kg",
      "KYORUGI,Female,U16,-59kg",
      "KYORUGI,Female,U16,-64kg",
      "KYORUGI,Female,U16,-69kg",
      "KYORUGI,Male,U19,-45kg",
      "KYORUGI,Male,U19,-48kg",
      "KYORUGI,Male,U19,-52kg",
      "KYORUGI,Male,U19,-56kg",
      "KYORUGI,Male,U19,60kg",
      "KYORUGI,Male,U19,-65kg",
      "KYORUGI,Male,U19,-71kg",
      "KYORUGI,Male,U19,-77kg",
      "KYORUGI,Male,U19,-85kg",
      "KYORUGI,Male,U19,-95kg",
      "KYORUGI,Female,U19,-42kg",
      "KYORUGI,Female,U19,-44kg",
      "KYORUGI,Female,U19,-46kg",
      "KYORUGI,Female,U19,-49kg",
      "KYORUGI,Female,U19,-54kg",
      "KYORUGI,Female,U19,-59kg",
      "KYORUGI,Female,U19,-64kg",
      "KYORUGI,Female,U19,-69kg",
      "KYORUGI,Female,U19,-75kg",
      "KYORUGI,Female,U19,-85kg",
      "KYORUGI,Male,U29,-45kg",
      "KYORUGI,Male,U29,-48kg",
      "KYORUGI,Male,U29,-52kg",
      "KYORUGI,Male,U29,-56kg",
      "KYORUGI,Male,U29,60kg",
      "KYORUGI,Male,U29,-65kg",
      "KYORUGI,Male,U29,-71kg",
      "KYORUGI,Male,U29,-77kg",
      "KYORUGI,Male,U29,-85kg",
      "KYORUGI,Male,U29,-95kg",
      "KYORUGI,Female,U29,-42kg",
      "KYORUGI,Female,U29,-44kg",
      "KYORUGI,Female,U29,-46kg",
      "KYORUGI,Female,U29,-49kg",
      "KYORUGI,Female,U29,-54kg",
      "KYORUGI,Female,U29,-59kg",
      "KYORUGI,Female,U29,-64kg",
      "KYORUGI,Female,U29,-69kg",
      "KYORUGI,Female,U29,-75kg",
      "KYORUGI,Female,U29,-85kg"
    ],
    "publicViewPassword": "sttc2",
    "packageSubsequentEventFee": "20",
    "poomsaeFee": "80",
    "bankAccount": "601221609001",
    "kyorugiFee": "80",
    "virtualFee": "",
    "name": "ST TERESA CUP 2026",
    "events": [
      "Kyorugi",
      "Para Kyorugi",
      "Recognize Poomsae",
      "Free Style Poomsae",
      "Para Poomsae",
      "Virtual Taekwondo",
      "Kyukpa",
      "Speed Kicking",
      "Skipping Rope",
      "Recognize Poomsae 2"
    ]
  },
  {
    "date": "2026-09-12",
    "name": "TM National Remaja 2026",
    "isActive": true,
    "weightClasses": [
      "All Colour Belt",
      "BANTAM 21.01KG-24KG",
      "BANTAM 23.01KG-26KG",
      "BANTAM 33.01KG-37KG",
      "BANTAM 37.01KG-41KG",
      "BANTAM 44.01KG-46KG",
      "BANTAM 48.01KG-51KG",
      "FEATHER 24.01KG-27KG",
      "FEATHER 26.01KG-29KG",
      "FEATHER 37.01KG-41KG",
      "FEATHER 41.01KG-45KG",
      "FEATHER 46.01KG-49KG",
      "FEATHER 51.01KG-55KG",
      "FIN BELOW 18KG",
      "FIN BELOW 20KG",
      "FIN BELOW 29KG",
      "FIN BELOW 33KG",
      "FIN BELOW 42KG",
      "FIN BELOW 45KG",
      "FLY 18.01KG-21KG",
      "FLY 20.01KG-23KG",
      "FLY 29.01KG-33KG",
      "FLY 33.01KG-37KG",
      "FLY 42.01KG-44KG",
      "FLY 45.01KG-48KG",
      "HEAVY 38KG & ABOVE",
      "HEAVY 40KG & ABOVE",
      "HEAVY 59KG & ABOVE",
      "HEAVY 65KG & ABOVE",
      "HEAVY 68KG & ABOVE",
      "HEAVY 78KG & ABOVE",
      "LIGHT 27.01KG-30KG",
      "LIGHT 29.01KG-32KG",
      "LIGHT 41.01KG-44KG",
      "LIGHT 45.01KG-49KG",
      "LIGHT 49.01KG-52KG",
      "LIGHT 55.01KG-59KG",
      "LIGHT HEAVY 55.01KG-59KG",
      "LIGHT HEAVY 61.01KG-65KG",
      "LIGHT HEAVY 63.01KG-68KG",
      "LIGHT HEAVY 73.01KG-78KG",
      "LIGHT MIDDLE 47.01KG-51KG",
      "LIGHT MIDDLE 53.01KG-57KG",
      "LIGHT MIDDLE 55.01KG-59KG",
      "LIGHT MIDDLE 63.01KG-68KG",
      "MIDDLE 34.01KG-38KG",
      "MIDDLE 36.01KG-40KG",
      "MIDDLE 51.01KG-55KG",
      "MIDDLE 57.01KG-61KG",
      "MIDDLE 59.01KG-63KG",
      "MIDDLE 68.01KG-73KG",
      "Not Exceeding 58KG",
      "Open Weight",
      "Over 65KG",
      "P21",
      "P22",
      "P23",
      "Taegeuk 4 to Koryo",
      "Taegeuk 4 to Taebaek",
      "Taegeuk 5 to Pyongwon",
      "WELTER 30.01KG-34KG",
      "WELTER 32.01KG-36KG",
      "WELTER 44.01KG-47KG",
      "WELTER 49.01KG-53KG",
      "WELTER 52.01KG-55KG",
      "WELTER 59.01KG-63KG"
    ],
    "affiliatedClubs": [
      "SMART MA TAEKWONDO CLUB",
      "SAUJANA TKD CLUB",
      "TYC TAEKWONDO CLUB",
      "MATSA TAEKWONDO CLUB",
      "PUSAT SENI MEMPERTAHANKAN DIRI TAEKWONDO ACTION WTF",
      "KORYO TAEKWONDO CLUB"
    ],
    "staffCode": "weighin123",
    "id": "tmremaja2026",
    "genders": [
      "Male",
      "Female",
      "Mix"
    ],
    "ageGroups": [
      "Super Cadet (9 To 10 Years Old)",
      "Super Cadet (9 to 11 Years Old)",
      "Cadet (11 to 12 Years Old)",
      "Cadet (12 to 14 Years Old)",
      "Junior (13 to 14 Years Old)",
      "Junior (15 to 17 Years Old)",
      "12 to 14 Years Old",
      "15 to 17 Years Old",
      "16 years & Older"
    ],
    "events": [
      "Kyorugi",
      "Para Kyorugi",
      "Recognize Poomsae",
      "Recognize Poomsae 2",
      "Free Style Poomsae",
      "Para Poomsae",
      "Virtual Taekwondo",
      "Kyukpa",
      "Speed Kicking",
      "Skipping Rope"
    ],
    "venue": "National Taekwondo Arena"
  },
  {
    "hideScaleReadout": true,
    "date": "2026-07-10",
    "staffCode": "1",
    "poomsaeFee": "",
    "venue": "Melaka",
    "events": [
      "Kyorugi",
      "Para Kyorugi",
      "Recognize Poomsae",
      "Free Style Poomsae",
      "Para Poomsae",
      "Virtual Taekwondo",
      "Kyukpa",
      "Speed Kicking",
      "Skipping Rope",
      "Recognize Poomsae 2"
    ],
    "virtualFee": "80",
    "kyorugiFee": "",
    "name": "Trial Championship",
    "isActive": true,
    "weightClasses": [
      "Flyweight:  58 kg",
      "Featherweight: 68 kg",
      "Welterweight: 80 kg",
      "Heavyweight: Over 80 kg"
    ],
    "publicViewPassword": "1",
    "idCardFields": [
      {
        "color": "#ffffff",
        "visible": true,
        "fontSize": "sm",
        "order": 0,
        "id": "header",
        "align": "center",
        "name": "Header Banner"
      },
      {
        "id": "name",
        "order": 1,
        "name": "Athlete Name",
        "color": "#ffffff",
        "fontSize": "lg",
        "align": "center",
        "visible": true
      },
      {
        "id": "photo",
        "order": 2,
        "name": "Athlete Portrait",
        "visible": true,
        "fontSize": "sm",
        "align": "center"
      },
      {
        "id": "club",
        "order": 3,
        "name": "Club / Team",
        "fontSize": "xs",
        "color": "#a0aec0",
        "align": "center",
        "visible": true
      },
      {
        "align": "center",
        "color": "#D4AF37",
        "id": "athleteId",
        "fontSize": "xs",
        "order": 4,
        "name": "Athlete ID Badge",
        "visible": true
      },
      {
        "align": "center",
        "fontSize": "sm",
        "color": "#ffffff",
        "name": "Metadata Grid",
        "id": "metadata",
        "order": 5,
        "visible": true
      },
      {
        "visible": true,
        "order": 6,
        "fontSize": "sm",
        "color": "#D4AF37",
        "name": "QR Code & Scan Info",
        "id": "qrcode",
        "align": "left"
      },
      {
        "visible": true,
        "fontSize": "sm",
        "order": 7,
        "align": "center",
        "id": "belt",
        "name": "Belt Accent Strip"
      }
    ],
    "ageGroups": [
      "9-11",
      "12-14",
      "15-17",
      "2-3"
    ],
    "paraFee": "",
    "id": "trialchampionshik6zx",
    "genders": [
      "Male",
      "Female",
      "Mix"
    ]
  },
  {
    "name": "Wukwon 2026",
    "date": "2026-07-18",
    "isActive": true,
    "weightClasses": [],
    "staffCode": "1",
    "id": "wukwon2026ygzk",
    "genders": [
      "Male",
      "Female",
      "Mix"
    ],
    "ageGroups": [],
    "registrationCloseDate": "",
    "events": [
      "Kyorugi",
      "Para Kyorugi",
      "Recognize Poomsae",
      "Free Style Poomsae",
      "Para Poomsae",
      "Virtual Taekwondo",
      "Kyukpa",
      "Speed Kicking",
      "Skipping Rope",
      "Recognize Poomsae 2"
    ],
    "venue": "JB",
    "endDate": "2026-07-19"
  }
];

export const BASELINE_TERESA_PLAYERS: Player[] = [
  {
    "weighIn": null,
    "dob": "2018-04-21",
    "race": "Chinese",
    "name": "Poh Xiang Rong, Elicia",
    "club": "GK Taekwondo Pte Ltd",
    "ic": "T1811871D",
    "createdAt": "2026-09-14T07:04:01.519Z",
    "compId": "stteresacup2026udkr",
    "schoolCode": "0",
    "schoolName": "GK Taekwondo",
    "coachUsername": "Atif Zulkiflee",
    "id": "PLY-17QRL",
    "gender": "Female",
    "event": "Recognize Poomsae",
    "ageGroup": "U8- 7 years old to 8 years old",
    "weightClass": "POOMSAE,Yellow 8 Taeguek 1"
  },
  {
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "ic": "111",
    "race": "Chinese",
    "name": "CEDRIC NATHAN OYANG",
    "indemnityParentEmail": "",
    "gender": "Male",
    "coachUsername": "veritastkd",
    "ageGroup": "U10-9 years old to 10 years old",
    "indemnityStatus": "Completed",
    "indemnityParentPhone": "+6582000856",
    "schoolName": "EAGLE RIAU",
    "schoolCode": "0",
    "event": "Recognize Poomsae",
    "weighIn": null,
    "weightClass": "POOMSAE,Green 6 Taeguek 3",
    "createdAt": "2026-09-15T04:18:31.006Z",
    "indemnitySignedIp": "Client-device",
    "indemnityParentName": "YULIANA",
    "dob": "2017-10-10",
    "compId": "stteresacup2026udkr",
    "indemnityRelationship": "Mother",
    "id": "PLY-1HE4H",
    "indemnitySignedDate": "15/09/2026, 12:21:02 pm",
    "indemnityParentIc": "123"
  },
  {
    "event": "Recognize Poomsae",
    "compId": "stteresacup2026udkr",
    "ic": "T1825774I",
    "weighIn": null,
    "dob": "2018-08-29",
    "schoolName": "GK Taekwondo",
    "schoolCode": "0",
    "id": "PLY-1YHS7",
    "createdAt": "2026-09-14T07:06:22.213Z",
    "coachUsername": "Atif Zulkiflee",
    "weightClass": "POOMSAE,Poom ,Koryo, Keumgang, Taebaek, Pyongwon,Sipjin",
    "race": "Chinese",
    "name": "Calder Yeoh Zhe Kai",
    "ageGroup": "U8- 7 years old to 8 years old",
    "club": "GK Taekwondo Pte Ltd",
    "gender": "Male"
  },
  {
    "club": "GK Taekwondo Pte Ltd",
    "ic": "T1932663I",
    "race": "Chinese",
    "name": "Jrisca Woo Ying En",
    "compId": "stteresacup2026udkr",
    "coachUsername": "Atif Zulkiflee",
    "weighIn": null,
    "weightClass": "POOMSAE,Green 5 Taeguek 4",
    "dob": "2019-11-06",
    "ageGroup": "U8- 7 years old to 8 years old",
    "schoolName": "GK Taekwondo",
    "schoolCode": "0",
    "id": "PLY-2DY0K",
    "gender": "Female",
    "createdAt": "2026-09-17T05:10:02.675Z",
    "event": "Recognize Poomsae"
  },
  {
    "ageGroup": "U10-9 years old to 10 years old",
    "coachUsername": "Atif Zulkiflee",
    "weightClass": "POOMSAE,Red 2 Taeguek 7",
    "weighIn": null,
    "gender": "Male",
    "event": "Recognize Poomsae",
    "ic": "T1717347I",
    "createdAt": "2026-09-10T09:29:14.487Z",
    "dob": "2017-06-18",
    "compId": "stteresacup2026udkr",
    "name": "Chua Jia You Clifton",
    "race": "Chinese",
    "id": "PLY-48SC6",
    "club": "GK Taekwondo Pte Ltd",
    "schoolCode": "0",
    "schoolName": "Gk Taekwondo"
  },
  {
    "weightClass": "POOMSAE,Dan, Koryo, Keumgang, Taebaek, Pyongwon,Sipjin",
    "indemnityParentEmail": "",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "race": "Others",
    "name": "CHRISTINAWATI",
    "compId": "stteresacup2026udkr",
    "id": "PLY-4A9FJ",
    "createdAt": "2026-09-09T04:06:40.165Z",
    "indemnityRelationship": "SELF",
    "indemnityParentPhone": "+6582000856",
    "dob": "1983-04-21",
    "weighIn": null,
    "indemnityStatus": "Completed",
    "indemnitySignedIp": "Client-device",
    "event": "Recognize Poomsae",
    "indemnityParentName": "CHRISTINAWATI",
    "ageGroup": "O30-30 years old and above",
    "indemnitySignedDate": "09/09/2026, 12:08:48 pm",
    "gender": "Female",
    "ic": "103",
    "coachUsername": "veritastkd",
    "indemnityParentIc": "123",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL"
  },
  {
    "createdAt": "2026-09-15T04:18:31.006Z",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "ageGroup": "U10-9 years old to 10 years old",
    "race": "Chinese",
    "name": "CEDRIC NATHAN OYANG",
    "indemnitySignedIp": "Client-device",
    "compId": "stteresacup2026udkr",
    "weighIn": null,
    "indemnityStatus": "Completed",
    "indemnityParentName": "YULIANA",
    "coachUsername": "veritastkd",
    "indemnitySignedDate": "15/09/2026, 12:22:38 pm",
    "ic": "111",
    "indemnityRelationship": "Mother",
    "schoolName": "EAGLE RIAU",
    "schoolCode": "0",
    "indemnityParentIc": "123",
    "dob": "2017-10-10",
    "id": "PLY-5DC7L",
    "indemnityParentPhone": "+6582000856",
    "weightClass": "KYUPKA, U6 & U8 & U10",
    "gender": "Male",
    "indemnityParentEmail": "",
    "event": "Kyukpa"
  },
  {
    "id": "PLY-7B9HK",
    "indemnityParentEmail": "",
    "schoolName": "EAGLE RIAU",
    "schoolCode": "0",
    "indemnityParentPhone": "+6582000856",
    "createdAt": "2026-09-15T21:17:15.906Z",
    "name": "CEDRIC NATHAN OYANG",
    "race": "Chinese",
    "gender": "Male",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "event": "Recognize Poomsae 2",
    "ageGroup": "U10-9 years old to 10 years old",
    "indemnityStatus": "Completed",
    "indemnityRelationship": "Mother",
    "indemnitySignedDate": "16/09/2026, 5:17:58 am",
    "weighIn": null,
    "compId": "stteresacup2026udkr",
    "indemnityParentIc": "123",
    "dob": "2017-10-10",
    "indemnitySignedIp": "Client-device",
    "weightClass": "POOMSAE,Yellow 7 Taeguek 2",
    "ic": "111",
    "indemnityParentName": "YULIANA",
    "coachUsername": "veritastkd"
  },
  {
    "indemnityParentName": "YULIANA",
    "schoolCode": "0",
    "schoolName": "EAGLE RIAU",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnitySignedIp": "Client-device",
    "name": "CEDRIC NATHAN OYANG",
    "race": "Chinese",
    "createdAt": "2026-09-15T04:18:31.006Z",
    "gender": "Male",
    "indemnityParentEmail": "",
    "indemnityRelationship": "Mother",
    "ageGroup": "U10-9 years old to 10 years old",
    "indemnitySignedDate": "15/09/2026, 12:25:32 pm",
    "id": "PLY-7N2HX",
    "indemnityParentPhone": "+6582000856",
    "indemnityParentIc": "123",
    "coachUsername": "veritastkd",
    "event": "Kyorugi",
    "ic": "111",
    "dob": "2017-10-10",
    "weighIn": null,
    "weightClass": "KYORUGI,Male,U6,-24kg",
    "compId": "stteresacup2026udkr",
    "indemnityStatus": "Completed"
  },
  {
    "indemnityRelationship": "self",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "compId": "stteresacup2026udkr",
    "createdAt": "2026-09-09T03:13:22.587Z",
    "coachUsername": "veritastkd",
    "weightClass": "POOMSAE,Yellow 8 Taeguek 1",
    "id": "PLY-7YZAX",
    "ageGroup": "O30-30 years old and above",
    "indemnitySignedIp": "Client-device",
    "ic": "123",
    "dob": "1983-10-25",
    "indemnityParentName": "JULIATI",
    "indemnityParentEmail": "",
    "indemnityStatus": "Completed",
    "indemnitySignedDate": "09/09/2026, 11:19:47 am",
    "indemnityParentPhone": "+6582000856",
    "gender": "Female",
    "event": "Recognize Poomsae",
    "indemnityParentIc": "123",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "weighIn": null,
    "race": "Others",
    "name": "JULIATI"
  },
  {
    "schoolName": "GK Taekwondo",
    "schoolCode": "0",
    "indemnitySignedIp": "Client-device",
    "weighIn": null,
    "event": "Kyorugi",
    "indemnityParentIc": "S8866377B",
    "gender": "Female",
    "ic": "T1870637C",
    "coachUsername": "Atif Zulkiflee",
    "id": "PLY-9FQ6C",
    "dob": "2018-10-30",
    "race": "Malay",
    "name": "Abby Lynn Choo Kleinbongardt",
    "ageGroup": "U8- 7 years old to 8 years old",
    "compId": "stteresacup2026udkr",
    "club": "GK Taekwondo Pte Ltd",
    "indemnitySignedDate": "17/09/2026, 1:39:15 PM",
    "indemnityParentPhone": "+6586616361",
    "indemnityRelationship": "Mother",
    "weightClass": "KYORUGI,Female,U6,-25kg",
    "createdAt": "2026-09-17T05:14:59.892Z",
    "indemnityParentName": "Amy choo Wei lynn",
    "indemnityStatus": "Completed",
    "indemnityParentEmail": "lynn_choo@yahoo.com"
  },
  {
    "id": "PLY-A7FXN",
    "indemnityParentPhone": "+6582000856",
    "weighIn": null,
    "coachUsername": "veritastkd",
    "createdAt": "2026-09-09T04:18:07.379Z",
    "compId": "stteresacup2026udkr",
    "indemnityParentEmail": "",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "schoolCode": "0",
    "weightClass": "POOMSAE,Yellow 8 Taeguek 1",
    "race": "Others",
    "name": "AMINAH",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "ageGroup": "O30-30 years old and above",
    "gender": "Female",
    "indemnityStatus": "Completed",
    "dob": "1995-10-05",
    "indemnityParentIc": "123",
    "event": "Recognize Poomsae",
    "indemnityRelationship": "SELF",
    "indemnityParentName": "AMINAH",
    "indemnitySignedIp": "Client-device",
    "indemnitySignedDate": "09/09/2026, 12:19:30 pm",
    "ic": "104"
  },
  {
    "club": "GK Taekwondo Pte Ltd",
    "ic": "T1203931F",
    "race": "Chinese",
    "name": "Poh Jing Xuan, Clarisa",
    "compId": "stteresacup2026udkr",
    "weighIn": null,
    "coachUsername": "Atif Zulkiflee",
    "weightClass": "POOMSAE,Poom ,Koryo, Keumgang, Taebaek, Pyongwon,Sipjin",
    "dob": "2012-02-11",
    "ageGroup": "U14-13 years old to 14 years old",
    "schoolName": "GK Taekwondo",
    "schoolCode": "0",
    "id": "PLY-BVSV4",
    "gender": "Female",
    "createdAt": "2026-09-14T07:02:29.156Z",
    "event": "Recognize Poomsae"
  },
  {
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "ic": "111",
    "name": "CEDRIC NATHAN OYANG",
    "race": "Chinese",
    "indemnityParentEmail": "",
    "gender": "Male",
    "ageGroup": "U10-9 years old to 10 years old",
    "coachUsername": "veritastkd",
    "indemnityStatus": "Completed",
    "indemnityParentPhone": "+6582000856",
    "schoolName": "EAGLE RIAU",
    "schoolCode": "0",
    "event": "Speed Kicking",
    "weighIn": null,
    "weightClass": "SPEED KICKING, U6 & U8 & U10",
    "indemnityParentName": "YULIANA",
    "indemnitySignedIp": "Client-device",
    "createdAt": "2026-09-15T04:18:31.006Z",
    "dob": "2017-10-10",
    "compId": "stteresacup2026udkr",
    "indemnityRelationship": "Mother",
    "id": "PLY-CGFK5",
    "indemnitySignedDate": "15/09/2026, 12:27:28 pm",
    "indemnityParentIc": "123"
  },
  {
    "schoolName": "GK Taekwondo",
    "schoolCode": "0",
    "race": "Chinese",
    "name": "Liel Michael Susanto",
    "club": "GK Taekwondo Pte Ltd",
    "id": "PLY-ELT7E",
    "compId": "stteresacup2026udkr",
    "weighIn": null,
    "weightClass": "POOMSAE,Yellow 8 Taeguek 1",
    "createdAt": "2026-09-14T06:59:41.945Z",
    "event": "Recognize Poomsae",
    "ageGroup": "U8- 7 years old to 8 years old",
    "coachUsername": "Atif Zulkiflee",
    "dob": "2018-03-27",
    "gender": "Male",
    "ic": "T1808683I"
  },
  {
    "ageGroup": "O30-30 years old and above",
    "id": "PLY-H7LTP",
    "indemnityParentIc": "123",
    "indemnityRelationship": "SELF",
    "indemnitySignedIp": "Client-device",
    "weightClass": "KYUPKA, U29 & O30",
    "coachUsername": "veritastkd",
    "compId": "stteresacup2026udkr",
    "indemnityStatus": "Completed",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "schoolCode": "0",
    "gender": "Female",
    "name": "PARIDA",
    "race": "Others",
    "indemnityParentPhone": "+6582000856",
    "indemnitySignedDate": "09/09/2026, 12:39:56 pm",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "weighIn": null,
    "event": "Kyukpa",
    "dob": "1983-06-18",
    "indemnityParentName": "PARIDA",
    "createdAt": "2026-09-09T04:39:06.413Z",
    "indemnityParentEmail": "",
    "ic": "108"
  },
  {
    "createdAt": "2026-09-09T04:22:31.174Z",
    "compId": "stteresacup2026udkr",
    "event": "Recognize Poomsae",
    "indemnitySignedIp": "Client-device",
    "indemnityRelationship": "SELF",
    "id": "PLY-JM2V7",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnityParentIc": "123",
    "coachUsername": "veritastkd",
    "weightClass": "POOMSAE,Green 6 Taeguek 3",
    "indemnityParentEmail": "",
    "weighIn": null,
    "ic": "105",
    "indemnityStatus": "Completed",
    "indemnityParentName": "YASMINE",
    "name": "YASMINE",
    "race": "Others",
    "ageGroup": "O30-30 years old and above",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnityParentPhone": "+6582000856",
    "indemnitySignedDate": "09/09/2026, 12:23:15 pm",
    "dob": "1975-10-06",
    "gender": "Female"
  },
  {
    "indemnityParentIc": "123",
    "ic": "108",
    "createdAt": "2026-09-09T04:39:06.413Z",
    "coachUsername": "veritastkd",
    "weighIn": null,
    "event": "Recognize Poomsae",
    "compId": "stteresacup2026udkr",
    "indemnitySignedIp": "Client-device",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "name": "PARIDA",
    "race": "Others",
    "indemnityRelationship": "SELF",
    "indemnityStatus": "Completed",
    "weightClass": "POOMSAE,Green 5 Taeguek 4",
    "dob": "1983-06-18",
    "indemnityParentName": "PARIDA",
    "indemnityParentEmail": "",
    "gender": "Female",
    "indemnitySignedDate": "09/09/2026, 12:40:46 pm",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnityParentPhone": "+6582000856",
    "id": "PLY-JN8JE",
    "ageGroup": "O30-30 years old and above"
  },
  {
    "ic": "101",
    "indemnityParentEmail": "",
    "indemnitySignedIp": "Client-device",
    "compId": "stteresacup2026udkr",
    "weightClass": "KYUPKA, U29 & O30",
    "indemnityParentIc": "123",
    "indemnityParentPhone": "+6582000856",
    "dob": "1986-01-28",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "race": "Indian",
    "name": "PRAJAKTA BHALEKAR",
    "indemnityParentName": "PRAJAKTA BHALEKAR",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "schoolCode": "0",
    "indemnityRelationship": "SELF",
    "event": "Kyukpa",
    "indemnityStatus": "Completed",
    "gender": "Female",
    "coachUsername": "veritastkd",
    "weighIn": null,
    "id": "PLY-K2ZRR",
    "indemnitySignedDate": "09/09/2026, 11:52:15 am",
    "ageGroup": "O30-30 years old and above",
    "createdAt": "2026-09-09T03:51:12.474Z"
  },
  {
    "indemnityParentIc": "123",
    "indemnityParentEmail": "",
    "weighIn": null,
    "event": "Kyukpa",
    "indemnityStatus": "Completed",
    "coachUsername": "veritastkd",
    "id": "PLY-N0WDK",
    "indemnitySignedIp": "Client-device",
    "compId": "stteresacup2026udkr",
    "dob": "1988-03-23",
    "indemnityParentPhone": "+6582000856",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "gender": "Female",
    "name": "SHERLYN DJUKA",
    "race": "Others",
    "ic": "100",
    "indemnityRelationship": "SELF",
    "indemnitySignedDate": "09/09/2026, 11:27:25 am",
    "ageGroup": "O30-30 years old and above",
    "weightClass": "KYUPKA, U29 & O30",
    "createdAt": "2026-09-09T03:25:27.445Z",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO SINGAPORE",
    "indemnityParentName": "SHERLYN DJUKA"
  },
  {
    "dob": "1995-10-05",
    "event": "Kyukpa",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnityParentEmail": "",
    "race": "Others",
    "name": "AMINAH",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnityParentPhone": "+6582000856",
    "gender": "Female",
    "ic": "104",
    "compId": "stteresacup2026udkr",
    "indemnitySignedDate": "09/09/2026, 12:20:18 pm",
    "id": "PLY-NPIP6",
    "indemnityParentIc": "123",
    "ageGroup": "O30-30 years old and above",
    "weighIn": null,
    "createdAt": "2026-09-09T04:18:07.379Z",
    "weightClass": "KYUPKA, U29 & O30",
    "indemnitySignedIp": "Client-device",
    "coachUsername": "veritastkd",
    "indemnityRelationship": "SELF",
    "indemnityStatus": "Completed",
    "indemnityParentName": "AMINAH"
  },
  {
    "ageGroup": "U16-15 years old to 16 years old",
    "coachUsername": "Atif Zulkiflee",
    "weighIn": null,
    "schoolCode": "0",
    "schoolName": "GK Taekwondo",
    "compId": "stteresacup2026udkr",
    "createdAt": "2026-09-14T07:08:04.526Z",
    "id": "PLY-PD2XR",
    "event": "Recognize Poomsae",
    "gender": "Female",
    "club": "GK Taekwondo Pte Ltd",
    "dob": "2011-09-12",
    "ic": "T1126528B",
    "name": "Lum Jia Qi Jolee",
    "race": "Chinese",
    "weightClass": "POOMSAE,Poom ,Koryo, Keumgang, Taebaek, Pyongwon,Sipjin"
  },
  {
    "club": "GK Taekwondo Pte Ltd",
    "name": "Benson Wong",
    "race": "Chinese",
    "createdAt": "2026-09-15T03:51:41.894Z",
    "indemnityStatus": "Completed",
    "gender": "Male",
    "indemnityParentIc": "S7940050E",
    "ageGroup": "U19-17 years old to 19 years old",
    "indemnitySignedIp": "Client-device",
    "ic": "T0904998Z",
    "dob": "2009-01-30",
    "event": "Kyorugi",
    "weighIn": null,
    "indemnityRelationship": "Mother",
    "schoolCode": "0",
    "schoolName": "GK Taekwondo",
    "indemnityParentPhone": "90674311",
    "indemnitySignedDate": "17/09/2026, 2:01:33 PM",
    "id": "PLY-PM59H",
    "indemnityParentName": "Jade low",
    "compId": "stteresacup2026udkr",
    "indemnityParentEmail": "",
    "weightClass": "KYORUGI,Male,U19,-56kg",
    "coachUsername": "Atif Zulkiflee"
  },
  {
    "indemnitySignedIp": "Client-device",
    "weighIn": null,
    "indemnityRelationship": "SELF",
    "dob": "1986-01-28",
    "createdAt": "2026-09-09T03:51:12.474Z",
    "gender": "Female",
    "id": "PLY-RNAWC",
    "indemnityParentIc": "123",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "schoolCode": "0",
    "poomsaePattern": "Koryo & Above (Black Belt)",
    "weightClass": "POOMSAE,Dan, Koryo, Keumgang, Taebaek, Pyongwon,Sipjin",
    "coachUsername": "veritastkd",
    "name": "PRAJAKTA BHALEKAR",
    "race": "Indian",
    "ic": "101",
    "indemnityParentEmail": "",
    "indemnitySignedDate": "09/09/2026, 11:53:21 am",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "event": "Recognize Poomsae",
    "indemnityParentName": "PRAJAKTA BHALEKAR",
    "indemnityParentPhone": "+6582000856",
    "indemnityStatus": "Completed",
    "compId": "stteresacup2026udkr",
    "ageGroup": "O30-30 years old and above"
  },
  {
    "indemnityRelationship": "SELF",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "compId": "stteresacup2026udkr",
    "createdAt": "2026-09-09T03:13:22.587Z",
    "coachUsername": "veritastkd",
    "weightClass": "KYUPKA, U29 & O30",
    "id": "PLY-T3Z3U",
    "ageGroup": "O30-30 years old and above",
    "indemnitySignedIp": "Client-device",
    "ic": "123",
    "dob": "1983-10-25",
    "indemnityParentName": "JULIATI",
    "indemnityParentEmail": "",
    "indemnityStatus": "Completed",
    "indemnitySignedDate": "09/09/2026, 11:21:29 am",
    "indemnityParentPhone": "+6582000856",
    "gender": "Female",
    "event": "Kyukpa",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnityParentIc": "123",
    "weighIn": null,
    "race": "Others",
    "name": "JULIATI"
  },
  {
    "compId": "stteresacup2026udkr",
    "weightClass": "POOMSAE,Yellow 8 Taeguek 1",
    "createdAt": "2026-09-09T03:25:27.445Z",
    "indemnityStatus": "Completed",
    "indemnityParentPhone": "+6582000856",
    "weighIn": null,
    "coachUsername": "veritastkd",
    "indemnityParentName": "SHERLYN DJUKA",
    "ic": "100",
    "indemnityParentEmail": "",
    "indemnitySignedDate": "09/09/2026, 11:28:25 am",
    "schoolName": "VERITAS TAEKWONDO SINGAPORE",
    "schoolCode": "0",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "name": "SHERLYN DJUKA",
    "race": "Others",
    "dob": "1988-03-23",
    "id": "PLY-U6IR2",
    "indemnityParentIc": "123",
    "indemnityRelationship": "SELF",
    "event": "Recognize Poomsae",
    "indemnitySignedIp": "Client-device",
    "ageGroup": "O30-30 years old and above",
    "gender": "Female"
  },
  {
    "schoolName": "GK Taekwondo",
    "schoolCode": "0",
    "coachUsername": "Atif Zulkiflee",
    "compId": "stteresacup2026udkr",
    "weighIn": null,
    "event": "Recognize Poomsae",
    "createdAt": "2026-09-15T09:58:06.278Z",
    "ic": "T1920301D",
    "id": "PLY-V07PN",
    "ageGroup": "U8- 7 years old to 8 years old",
    "weightClass": "POOMSAE,Yellow 8 Taeguek 1",
    "race": "Chinese",
    "name": "Harper Jun Leung",
    "club": "GK Taekwondo Pte Ltd",
    "dob": "2019-07-14",
    "gender": "Female"
  },
  {
    "indemnityParentName": "HELENA RAMBU KADUNGA ROBU",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnitySignedIp": "Client-device",
    "name": "HELENA RAMBU KADUNGA ROBU",
    "race": "Others",
    "createdAt": "2026-09-09T04:27:26.041Z",
    "gender": "Female",
    "indemnityParentEmail": "",
    "indemnityRelationship": "SELF",
    "ageGroup": "O30-30 years old and above",
    "indemnitySignedDate": "09/09/2026, 12:28:22 pm",
    "id": "PLY-XGCL3",
    "indemnityParentPhone": "+6582000856",
    "indemnityParentIc": "123",
    "coachUsername": "veritastkd",
    "event": "Recognize Poomsae",
    "ic": "106",
    "dob": "1991-10-04",
    "weighIn": null,
    "weightClass": "POOMSAE,Green 6 Taeguek 3",
    "compId": "stteresacup2026udkr",
    "indemnityStatus": "Completed"
  },
  {
    "race": "Chinese",
    "name": "Koh Hin Wei",
    "weightClass": "KYORUGI,Male,U29,-85kg",
    "gender": "Male",
    "club": "GK Taekwondo Pte Ltd",
    "coachUsername": "Atif Zulkiflee",
    "createdAt": "2026-09-17T05:19:24.497Z",
    "ic": "T0036578A",
    "ageGroup": "U29-20 years old to 29 years old",
    "id": "PLY-XNMT5",
    "dob": "2000-10-20",
    "weighIn": null,
    "schoolName": "GK Taekwondo",
    "schoolCode": "0",
    "event": "Kyorugi",
    "compId": "stteresacup2026udkr"
  },
  {
    "indemnityParentName": "YASMINE",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnitySignedIp": "Client-device",
    "race": "Others",
    "name": "YASMINE",
    "createdAt": "2026-09-09T04:22:31.174Z",
    "gender": "Female",
    "indemnityParentEmail": "",
    "ageGroup": "O30-30 years old and above",
    "indemnityRelationship": "SELF",
    "indemnitySignedDate": "09/09/2026, 12:23:59 pm",
    "indemnityParentPhone": "+6582000856",
    "id": "PLY-ZDTO5",
    "indemnityParentIc": "123",
    "coachUsername": "veritastkd",
    "event": "Kyukpa",
    "ic": "105",
    "dob": "1975-10-06",
    "weighIn": null,
    "weightClass": "KYUPKA, U29 & O30",
    "compId": "stteresacup2026udkr",
    "indemnityStatus": "Completed"
  },
  {
    "indemnityStatus": "Completed",
    "createdAt": "2026-09-09T04:31:05.270Z",
    "coachUsername": "veritastkd",
    "ic": "107",
    "ageGroup": "U29-20 years old to 29 years old",
    "gender": "Female",
    "dob": "2000-06-10",
    "compId": "stteresacup2026udkr",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "race": "Others",
    "name": "DWI JUNIARNI",
    "indemnitySignedDate": "09/09/2026, 12:31:57 pm",
    "indemnityParentPhone": "+6582000856",
    "indemnitySignedIp": "Client-device",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "id": "PLY-ZPTZ0",
    "weightClass": "KYUPKA, U29 & O30",
    "indemnityParentIc": "123",
    "indemnityRelationship": "SELF",
    "weighIn": null,
    "event": "Kyukpa",
    "indemnityParentName": "DWI JUNIARNI",
    "indemnityParentEmail": ""
  },
  {
    "createdAt": "2026-09-09T04:31:05.270Z",
    "ageGroup": "U29-20 years old to 29 years old",
    "weightClass": "POOMSAE,Yellow 8 Taeguek 1",
    "id": "PLY-ZS70V",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnitySignedDate": "09/09/2026, 12:32:47 pm",
    "name": "DWI JUNIARNI",
    "race": "Others",
    "indemnityRelationship": "SELF",
    "indemnityParentName": "DWI JUNIARNI",
    "compId": "stteresacup2026udkr",
    "indemnityStatus": "Completed",
    "event": "Recognize Poomsae",
    "schoolCode": "0",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnityParentIc": "123",
    "indemnityParentPhone": "+6582000856",
    "coachUsername": "veritastkd",
    "gender": "Female",
    "indemnitySignedIp": "Client-device",
    "ic": "107",
    "dob": "2000-06-10",
    "weighIn": null,
    "indemnityParentEmail": ""
  },
  {
    "indemnityParentIc": "123",
    "compId": "stteresacup2026udkr",
    "createdAt": "2026-09-09T04:27:26.041Z",
    "coachUsername": "veritastkd",
    "event": "Kyukpa",
    "weighIn": null,
    "indemnitySignedIp": "Client-device",
    "indemnityStatus": "Completed",
    "ic": "106",
    "dob": "1991-10-04",
    "id": "PLY-ZUCGJ",
    "race": "Others",
    "name": "HELENA RAMBU KADUNGA ROBU",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "indemnityRelationship": "SELF",
    "indemnitySignedDate": "09/09/2026, 12:29:29 pm",
    "indemnityParentPhone": "+6582000856",
    "ageGroup": "O30-30 years old and above",
    "indemnityParentName": "HELENA RAMBU KADUNGA ROBU",
    "gender": "Female",
    "weightClass": "KYUPKA, U29 & O30",
    "indemnityParentEmail": "",
    "schoolName": "VERITAS TAEKWONDO INTERNATIONAL",
    "schoolCode": "0"
  }
];

export const BASELINE_COACHES: Record<string, Coach> = {
  "123": {
    "name": "123",
    "username": "123",
    "password": "123",
    "club": "12345"
  },
  "Atif Zulkiflee": {
    "club": "Gk Taekwondo",
    "password": "Atif940303@",
    "username": "Atif Zulkiflee",
    "email": "atifzulkiflee@gmail.com",
    "phone": "+6013-4167119",
    "name": "Ahmad Atif Bin Zulkiflee"
  },
  "Induk Taekwondo": {
    "club": "Induk Taekwondo",
    "name": "Lee Na Lee",
    "phone": "+6580281066",
    "username": "Induk Taekwondo",
    "password": "weloveinduk123",
    "email": "frontdesk@induk.com.sg"
  },
  "RexT": {
    "club": "Taekwondonomics Pte Ltd",
    "phone": "+6597255047",
    "name": "Rex Rabbi Jude E. Tayco",
    "email": "REXRABBIJUDETAYCO@gmail.com",
    "password": "!Pinas211",
    "username": "RexT"
  },
  "Tony": {
    "phone": "0129506611",
    "name": "Tony",
    "email": "primajayataekwondo@gmailcom",
    "club": "Primajaya tkd club",
    "password": "primajaya",
    "username": "Tony"
  },
  "WoshinTKD_Andy": {
    "email": "woshintkd@gmail.com",
    "phone": "+6596219802",
    "name": "Andy Chin Zi An",
    "password": "Valandy99#",
    "username": "WoshinTKD_Andy",
    "club": "Woshin Taekwondo/Singapore"
  },
  "club_koryotaekwondoclub": {
    "password": "123",
    "username": "club_koryotaekwondoclub",
    "name": "Coach Koryo Taekwondo Club",
    "club": "KORYO TAEKWONDO CLUB"
  },
  "club_matsataekwondoclub": {
    "club": "MATSA TAEKWONDO CLUB",
    "name": "Coach Matsa Taekwondo Club",
    "password": "changeme123",
    "username": "club_matsataekwondoclub"
  },
  "club_pusatsenimempertahan": {
    "password": "changeme123",
    "name": "Coach Pusat Seni Mempertahankan Diri Taekwondo Action Wtf",
    "username": "club_pusatsenimempertahan",
    "club": "PUSAT SENI MEMPERTAHANKAN DIRI TAEKWONDO ACTION WTF"
  },
  "club_saujanatkdclub": {
    "username": "club_saujanatkdclub",
    "password": "123",
    "name": "Coach Saujana Tkd Club",
    "club": "SAUJANA TKD CLUB"
  },
  "club_smartmataekwondoclub": {
    "password": "changeme123",
    "username": "club_smartmataekwondoclub",
    "name": "Coach Smart Ma Taekwondo Club",
    "club": "SMART MA TAEKWONDO CLUB"
  },
  "club_tyctaekwondoclub": {
    "password": "changeme123",
    "username": "club_tyctaekwondoclub",
    "club": "TYC TAEKWONDO CLUB",
    "name": "Coach Tyc Taekwondo Club"
  },
  "demo": {
    "name": "Coach Demo",
    "password": "demo123",
    "username": "demo",
    "club": "SMART MA TAEKWONDO CLUB"
  },
  "elitesl": {
    "password": "bmw2011",
    "username": "elitesl",
    "email": "mahilwick25@gmail.com",
    "club": "ELITE TAEKWONDO SRI LANKA",
    "phone": "+94776936837",
    "name": "W A D M ASITHA WICKRAMATUNGA"
  },
  "mjtkdsg2026": {
    "name": "Mark Jovel Alcaldeza",
    "password": "mjtkdteam",
    "username": "mjtkdsg2026",
    "club": "A Taekwondo HQ",
    "phone": "09152648824",
    "email": "odantkd@yahoo.com.ph"
  },
  "odantkdsg2026": {
    "email": "odantkd@yahoo.com.ph",
    "name": "Jay ar U. Odan",
    "password": "odantkdteam",
    "username": "odantkdsg2026",
    "club": "Odan Taekwondo Team",
    "phone": "+639773508440"
  },
  "prun65": {
    "password": "tsports2023!",
    "username": "prun65",
    "email": "prun65@yahoo.com",
    "name": "April Teo",
    "club": "Han-Lim Taekwondo",
    "phone": "+6596922537"
  },
  "veritastkd": {
    "name": "Bambang Suryaputra",
    "phone": "+6582000856",
    "email": "martial.arts.veritas@gmail.com",
    "club": "VERITAS TAEKWONDO INTERNATIONAL",
    "password": "P@s123sw0rd",
    "username": "veritastkd"
  },
  "yuan": {
    "password": "123",
    "username": "yuan",
    "club": "KORYO TAEKWONDO CLUB",
    "email": "jinyuan922@gmail.com",
    "name": "LEE KIM YUAN",
    "phone": "012-9681253"
  }
};

export const BASELINE_ORGANIZERS: Record<string, Organizer> = {
  "SMA": {
    "id": "SMA",
    "name": "SMA",
    "username": "SMA",
    "password": "1",
    "compId": "smartmaclosecham7z9a"
  },
  "STTC": {
    "compId": "stteresacup2026udkr",
    "id": "STTC",
    "name": "STTC",
    "password": "123",
    "username": "STTC"
  },
  "SUKMA": {
    "password": "111",
    "username": "SUKMA",
    "name": "SUKMA",
    "id": "SUKMA",
    "compId": "sukanmalaysia2027dfk"
  },
  "cuba": {
    "name": "cuba",
    "id": "cuba",
    "username": "cuba",
    "password": "123",
    "compId": "cubauip3"
  },
  "oc": {
    "password": "1",
    "username": "oc",
    "id": "oc",
    "name": "occcc",
    "compId": "virtualmalaysiav30k"
  },
  "wk": {
    "id": "wk",
    "compId": "wukwonchampionshnxvf",
    "password": "123",
    "username": "wk",
    "name": "wk"
  },
  "wkt": {
    "compId": "wukwonchampionshnxvf",
    "name": "wk",
    "id": "wkt",
    "username": "wkt",
    "password": "1"
  }
};

export const BASELINE_REFEREE_ACCOUNTS: Referee[] = [
  {
    "kyorugiStatus": "SR",
    "residentialLocation": "Taman Wangsa Permai, KL",
    "id": "GLOBAL_000313140945",
    "clubName": "MBW",
    "nric": "000313140945",
    "bankName": "MAYBANK",
    "carPlate": "VDC5035 / BRE7367",
    "compId": "GLOBAL",
    "createdAt": "2026-08-30T05:00:11.376Z",
    "phone": "0102015955",
    "accommodation": "No",
    "specialRole": "None",
    "fullName": "LIEW CHENG LIANG",
    "bankAccount": "562151428361",
    "distance": 88,
    "password": "Johnliang313@",
    "poomsaeStatus": "SR"
  },
  {
    "password": "Gkl2020#",
    "distance": 286,
    "poomsaeStatus": "NR",
    "bankAccount": "163064331989",
    "compId": "GLOBAL",
    "id": "GLOBAL_000809030379",
    "specialRole": "None",
    "createdAt": "2026-08-12T15:38:05.451Z",
    "fullName": "Goh Kheng Long",
    "accommodation": "No",
    "nric": "000809-03-0379",
    "bankName": "Maybank",
    "clubName": "Kelantan",
    "residentialLocation": "Bukit Jalil",
    "phone": "013-9831320",
    "carPlate": "TCR 2933",
    "kyorugiStatus": "NR"
  },
  {
    "accommodation": "No",
    "fullName": "NUR AZREENA BALQIS BINTI NORAMIN",
    "residentialLocation": "Selangor",
    "poomsaeStatus": "TR",
    "compId": "GLOBAL",
    "password": "2132002",
    "distance": 90,
    "id": "GLOBAL_020318011956",
    "phone": "0187771757",
    "kyorugiStatus": "SR",
    "bankAccount": "162375946462",
    "clubName": "SMART M.A",
    "createdAt": "2026-09-01T13:32:12.364Z",
    "specialRole": "None",
    "bankName": "Maybank",
    "nric": "020318011956",
    "carPlate": "WQW 3716"
  },
  {
    "bankName": "CIMB BANK",
    "clubName": "WIN LONG",
    "accommodation": "No",
    "compId": "GLOBAL",
    "carPlate": "JXS5514",
    "nric": "020320-01-0856",
    "poomsaeStatus": "NR",
    "id": "GLOBAL_020320010856",
    "kyorugiStatus": "SR",
    "phone": "0128072218",
    "bankAccount": "7651793839",
    "distance": 10,
    "password": "Ltz@020320",
    "residentialLocation": "JB",
    "createdAt": "2026-07-20T12:59:26.984Z",
    "specialRole": "None",
    "fullName": "LEONG TZE ZHEN"
  },
  {
    "accommodation": "No",
    "createdAt": "2026-07-21T08:08:56.062Z",
    "distance": 50,
    "password": "Aa2811610370",
    "specialRole": "None",
    "phone": "0127391115",
    "bankAccount": "151101502671",
    "poomsaeStatus": "TR",
    "id": "GLOBAL_041121010194",
    "fullName": "LAM PANNY",
    "clubName": "WIN LONG TAEKWONDO",
    "bankName": "MAYBANK",
    "carPlate": "",
    "kyorugiStatus": "SR",
    "compId": "GLOBAL",
    "nric": "041121-01-0194",
    "residentialLocation": "JOHOR"
  },
  {
    "poomsaeStatus": "TR",
    "password": "Leelok2005",
    "distance": 18,
    "compId": "GLOBAL",
    "nric": "050122-01-0043",
    "id": "GLOBAL_050122010043",
    "phone": "01156611080",
    "accommodation": "No",
    "residentialLocation": "Skudai, Johor",
    "fullName": "Lee Mun Lok",
    "clubName": "Wenwu Martial Art",
    "bankName": "Hong Leong Bank",
    "createdAt": "2026-07-20T12:45:42.417Z",
    "bankAccount": "39550551268",
    "carPlate": "Jyn 3181",
    "specialRole": "None",
    "kyorugiStatus": "TR"
  },
  {
    "fullName": "KIEW XUE EN",
    "kyorugiStatus": "TR",
    "id": "GLOBAL_060107010044",
    "password": "Startingwindows107",
    "distance": 40,
    "createdAt": "2026-07-20T13:57:22.504Z",
    "specialRole": "None",
    "accommodation": "No",
    "poomsaeStatus": "TR",
    "carPlate": "JSV 6044",
    "compId": "GLOBAL",
    "nric": "060107-01-0044",
    "residentialLocation": "Kulai, Johor",
    "phone": "0102472949",
    "bankAccount": "5077669816",
    "clubName": "WIN LONG TAEKWONDO CLUB",
    "bankName": "PUBLIC BANK"
  },
  {
    "kyorugiStatus": "SR",
    "fullName": "NG YU FENG",
    "bankAccount": "5092226204",
    "specialRole": "None",
    "distance": 30,
    "password": "125yufeng2006",
    "residentialLocation": "Johor Bahru,Johor",
    "id": "GLOBAL_060125011219",
    "accommodation": "No",
    "phone": "01160538801",
    "nric": "060125-01-1219",
    "clubName": "ELITE TAEKWONDO CLUB",
    "poomsaeStatus": "TR",
    "bankName": "Public Bank",
    "carPlate": "JNB6321",
    "compId": "GLOBAL",
    "createdAt": "2026-07-20T12:43:19.079Z"
  },
  {
    "distance": 24,
    "password": "Haariesh20060617",
    "kyorugiStatus": "SR",
    "nric": "060617-01-1215",
    "residentialLocation": "JOHOR",
    "fullName": "HAARIESH A/L MAGESWARAN",
    "createdAt": "2026-07-20T13:22:28.338Z",
    "phone": "01128400856",
    "carPlate": "VQV 7623",
    "id": "GLOBAL_060617011215",
    "compId": "GLOBAL",
    "bankName": "Maybank",
    "clubName": "ELITE TAEKWONDO CLUB JOHOR",
    "accommodation": "No",
    "bankAccount": "1511 0160 7653",
    "specialRole": "None",
    "poomsaeStatus": "TR"
  },
  {
    "clubName": "NEWGEN TAEKWONDO CLUB",
    "bankName": "Public Bank",
    "kyorugiStatus": "SR",
    "carPlate": "WPA 3863",
    "id": "GLOBAL_060709101496",
    "compId": "GLOBAL",
    "nric": "060709-10-1496",
    "phone": "011-16399263",
    "residentialLocation": "Kepong, Kuala Lumpur",
    "createdAt": "2026-09-01T04:48:03.587Z",
    "bankAccount": "5116404622",
    "accommodation": "No",
    "password": "Xiner@2006",
    "distance": 104,
    "specialRole": "None",
    "poomsaeStatus": "TR",
    "fullName": "Wong Xin Er"
  },
  {
    "accommodation": "Yes",
    "bankAccount": "8881059792611",
    "phone": "0137208550",
    "hotelCheckoutDate": "N/A",
    "distance": 660,
    "password": "llyran1126",
    "compId": "GLOBAL",
    "accommodationDetails": "",
    "poomsaeStatus": "SR",
    "fullName": "TANG QIAO EN",
    "specialRole": "None",
    "id": "GLOBAL_060927012184",
    "bankName": "Ambank",
    "clubName": "Wenwu",
    "hotelDaysProvided": 0,
    "residentialLocation": "Setapak, Wilayah Persekutuan Kuala Lumpur",
    "carPlate": "-",
    "kyorugiStatus": "SR",
    "createdAt": "2026-07-20T12:37:42.167Z",
    "nric": "060927-01-2184",
    "accommodationMapsLink": ""
  },
  {
    "distance": 25,
    "password": "Chow1001",
    "id": "GLOBAL_061001010630",
    "phone": "01163978711",
    "poomsaeStatus": "TR",
    "fullName": "CHOW XUE LING",
    "residentialLocation": "JOHOR",
    "accommodation": "No",
    "specialRole": "None",
    "carPlate": "BRE3313",
    "bankName": "Bank Simpanan Nasional",
    "compId": "GLOBAL",
    "clubName": "WIN LONG TAEKWONDO CLUB",
    "createdAt": "2026-07-20T13:56:17.986Z",
    "kyorugiStatus": "TR",
    "nric": "061001-01-0630",
    "bankAccount": "0111841100049620"
  },
  {
    "carPlate": "-",
    "clubName": "Elite Taekwondo Club",
    "accommodation": "No",
    "nric": "070901-01-1131",
    "phone": "011-27648133",
    "createdAt": "2026-07-20T13:06:38.449Z",
    "bankName": "Hong leong bank",
    "compId": "GLOBAL",
    "poomsaeStatus": "TR",
    "id": "GLOBAL_070901011131",
    "kyorugiStatus": "SR",
    "password": "070901",
    "distance": 22,
    "bankAccount": "12650320808",
    "fullName": "ABILLASH A/L MAGESWARAN",
    "residentialLocation": "Kulai, Johor",
    "specialRole": "None"
  },
  {
    "poomsaeStatus": "TR",
    "compId": "GLOBAL",
    "carPlate": "NEE 972",
    "bankName": "Maybank",
    "clubName": "WIN LONG TAEKWONDO CLUB",
    "id": "GLOBAL_071116011368",
    "accommodation": "No",
    "residentialLocation": "Johor",
    "nric": "071116-01-1368",
    "distance": 42,
    "password": "qqaazzxx",
    "specialRole": "None",
    "createdAt": "2026-07-20T14:07:22.503Z",
    "bankAccount": "1511 0161 4302",
    "phone": "0102114567",
    "fullName": "CHONG JIA XIN",
    "kyorugiStatus": "TR"
  },
  {
    "createdAt": "2026-07-21T06:27:58.145Z",
    "accommodation": "No",
    "fullName": "RAIHAN ARJUNA BIN ROSMAN",
    "id": "GLOBAL_090716010813",
    "specialRole": "None",
    "poomsaeStatus": "TR",
    "bankAccount": "+60137751193",
    "distance": 52.3,
    "password": "123456ARJUNA",
    "residentialLocation": "Pasir Gudang, Johor",
    "kyorugiStatus": "TR",
    "carPlate": "JPL 1997",
    "compId": "GLOBAL",
    "nric": "090716-01-0813",
    "phone": "019-723 0657",
    "clubName": "WU KWON TAEKWONDO CLUB",
    "bankName": "TNG"
  },
  {
    "phone": "019-578-7207",
    "distance": 33,
    "password": "HUANyee!@#620903",
    "accommodation": "No",
    "residentialLocation": "Subang, Selangor",
    "fullName": "KOK HUAN YEE",
    "poomsaeStatus": "TR",
    "carPlate": "BMY 9236",
    "kyorugiStatus": "TR",
    "specialRole": "None",
    "createdAt": "2026-09-04T11:29:59.965Z",
    "clubName": "SMART MA TAEKWONDO CLUB",
    "bankName": "-",
    "nric": "100620-16-0127",
    "id": "ACC_100620160127",
    "bankAccount": "-",
    "compId": "GLOBAL"
  },
  {
    "clubName": "Argentina",
    "kyorugiStatus": "SR",
    "bankName": "Bank of America",
    "phone": "0123456789",
    "nric": "123456123456",
    "carPlate": "",
    "residentialLocation": "Miami",
    "accommodation": "No",
    "specialRole": "None",
    "distance": 350,
    "password": "123456",
    "createdAt": "2026-07-20T12:13:17.381Z",
    "bankAccount": "12345678",
    "compId": "GLOBAL",
    "id": "GLOBAL_123456123456",
    "poomsaeStatus": "TR",
    "fullName": "Lionel Messi"
  },
  {
    "compId": "GLOBAL",
    "id": "GLOBAL_140828102686",
    "accommodation": "No",
    "bankName": "Hong Leong Bank",
    "createdAt": "2026-09-01T10:12:32.424Z",
    "nric": "140828-10-2686",
    "phone": "0195147097",
    "clubName": "Smart Ma Taekwondo Club",
    "carPlate": "BSD909",
    "poomsaeStatus": "TR",
    "kyorugiStatus": "TR",
    "fullName": "CHLOE LIM EN TONG",
    "bankAccount": "37400027631",
    "residentialLocation": "Selangor",
    "specialRole": "None",
    "distance": 60,
    "password": "chloe@0828"
  },
  {
    "createdAt": "2026-07-18T11:49:32.732Z",
    "distance": 90,
    "residentialLocation": "KLUANG",
    "id": "GLOBAL_230501010308",
    "fullName": "HIEW KE XIN",
    "compId": "GLOBAL",
    "kyorugiStatus": "SR",
    "nric": "230501010308",
    "carPlate": "",
    "phone": "0189230501",
    "poomsaeStatus": "TR",
    "clubName": "JOHOR",
    "bankName": "GXBANK",
    "specialRole": "None",
    "accommodation": "No",
    "bankAccount": "112205040000"
  },
  {
    "poomsaeStatus": "IR",
    "hotelCheckoutDate": "Monday",
    "compId": "GLOBAL",
    "phone": "0168159818",
    "accommodationMapsLink": "",
    "carPlate": "Na",
    "accommodation": "Yes",
    "createdAt": "2026-07-20T14:29:39.580Z",
    "clubName": "MBVTC, Sabah",
    "nric": "580502-12-5457",
    "bankName": "Maybank",
    "residentialLocation": "Kota Kinabalu, Sabah",
    "fullName": "WONG TSU CHING",
    "specialRole": "None",
    "hotelDaysProvided": 3,
    "id": "GLOBAL_580502125457",
    "accommodationDetails": "",
    "bankAccount": "110077025900",
    "password": "800831",
    "distance": 1000,
    "kyorugiStatus": "IR"
  },
  {
    "bankAccount": "028-50-19914-5",
    "residentialLocation": "Selangor",
    "clubName": "SMART MA TAEKWONDO CLUB",
    "compId": "GLOBAL",
    "bankName": "Hong Leong Bank",
    "phone": "0123839961",
    "kyorugiStatus": "NR",
    "id": "GLOBAL_710217105337",
    "carPlate": "NEF 9293",
    "specialRole": "None",
    "poomsaeStatus": "NR",
    "fullName": "LIM KIM FATT",
    "nric": "710217-10-5337",
    "accommodation": "No",
    "createdAt": "2026-09-01T02:21:36.737Z",
    "password": "mjl123",
    "distance": 80
  },
  {
    "clubName": "Jaguar Taekwondo Club",
    "poomsaeStatus": "TR",
    "bankName": "CIMB",
    "carPlate": "JNN 1801",
    "accommodation": "No",
    "bankAccount": "7053304670",
    "id": "GLOBAL_710305015059",
    "createdAt": "2026-07-20T14:50:27.815Z",
    "phone": "0167805371",
    "distance": 50,
    "password": "277402",
    "nric": "710305015059",
    "residentialLocation": "Johor Bahru",
    "fullName": "KODESPERAN A/L THANGAVELOO",
    "compId": "GLOBAL",
    "kyorugiStatus": "TR",
    "specialRole": "None"
  },
  {
    "kyorugiStatus": "NR",
    "password": "bme1757",
    "distance": 90,
    "phone": "0133909636",
    "fullName": "ZAHUREEN BINTI ABDUL WAHID",
    "createdAt": "2026-09-01T13:01:51.780Z",
    "carPlate": "WQW 3716",
    "residentialLocation": "Sepang Selangor",
    "id": "GLOBAL_740119016792",
    "nric": "740119016792",
    "bankName": "Affin Bank",
    "accommodation": "No",
    "clubName": "SMART M. A",
    "specialRole": "None",
    "compId": "GLOBAL",
    "bankAccount": "ACCT NO.206620018470",
    "poomsaeStatus": "SR"
  },
  {
    "bankName": "CIMB",
    "phone": "+60162321253",
    "clubName": "MELAKA",
    "accommodation": "No",
    "id": "ACC_790124055425",
    "carPlate": "WB5908P",
    "createdAt": "2026-08-19T15:53:40.543Z",
    "bankAccount": "7027774861",
    "specialRole": "RIC",
    "nric": "790124055425",
    "poomsaeStatus": "IR",
    "kyorugiStatus": "IR",
    "residentialLocation": "ALOR GAJAH",
    "compId": "GLOBAL",
    "password": "lee093",
    "distance": 230,
    "fullName": "LEE EIT SENG",
    "updatedAt": "2026-09-03T04:03:00.082Z"
  },
  {
    "nric": "820211145327",
    "kyorugiStatus": "NR",
    "bankName": "Public bank",
    "clubName": "MATSA",
    "bankAccount": "6101017107",
    "carPlate": "ALG7440",
    "compId": "GLOBAL",
    "accommodationMapsLink": "",
    "accommodationDetails": "",
    "specialRole": "None",
    "hotelCheckoutDate": "Monday",
    "password": "Alex1102",
    "distance": 658,
    "accommodation": "Yes",
    "residentialLocation": "Sentul KL",
    "phone": "0172287658",
    "createdAt": "2026-07-20T12:36:55.577Z",
    "hotelDaysProvided": 3,
    "fullName": "LIM BOON KEONG",
    "id": "GLOBAL_820211145327",
    "poomsaeStatus": "SR"
  },
  {
    "distance": 220,
    "bankAccount": "551061337443",
    "accommodationDetails": "",
    "fullName": "HIEW SHEN CHON",
    "specialRole": "RIC",
    "kyorugiStatus": "IR",
    "hotelCheckoutDate": "Sunday",
    "phone": "0173355750",
    "carPlate": "JWY2292",
    "accommodationMapsLink": "",
    "poomsaeStatus": "NR",
    "compId": "GLOBAL",
    "bankName": "MAYBANK",
    "residentialLocation": "Kluang",
    "clubName": "TEMATA",
    "createdAt": "2026-07-23T13:32:26.180Z",
    "id": "ACC_820904016499",
    "nric": "820904016499",
    "accommodation": "Yes",
    "hotelDaysProvided": 2
  },
  {
    "residentialLocation": "Ampang, Selangor",
    "compId": "GLOBAL",
    "id": "GLOBAL_820914105321",
    "fullName": "MOHD ZATUL IKRAM BIN MOHD DIAH",
    "specialRole": "None",
    "bankAccount": "7610739485",
    "kyorugiStatus": "NR",
    "password": "Zuhaily#10",
    "distance": 12,
    "phone": "0198779653",
    "nric": "820914-10-5321",
    "poomsaeStatus": "TR",
    "createdAt": "2026-09-01T06:21:59.887Z",
    "bankName": "CIMB Bank",
    "clubName": "TKL / A-Team Martial Arts Academy",
    "accommodation": "No",
    "carPlate": "DDF1241"
  },
  {
    "specialRole": "None",
    "poomsaeStatus": "TR",
    "carPlate": "BLQ 9183",
    "phone": "0172899317",
    "bankName": "MAYBANK",
    "id": "GLOBAL_881007105271",
    "clubName": "Bandar Klang Taekwondo Club",
    "accommodation": "Yes",
    "nric": "881007105271",
    "hotelDaysProvided": 3,
    "bankAccount": "164155590297",
    "password": "881007",
    "distance": 706,
    "createdAt": "2026-07-20T13:43:56.024Z",
    "compId": "GLOBAL",
    "fullName": "PONG KOK LIANG",
    "accommodationMapsLink": "",
    "accommodationDetails": "",
    "residentialLocation": "Klang, Selangor",
    "hotelCheckoutDate": "monday",
    "kyorugiStatus": "IR"
  },
  {
    "fullName": "ERIC LEONG",
    "createdAt": "2026-07-20T15:00:05.590Z",
    "residentialLocation": "KL",
    "kyorugiStatus": "IR",
    "hotelCheckoutDate": "Monday",
    "accommodationMapsLink": "",
    "distance": 662,
    "password": "Eric@890117",
    "nric": "890117145439",
    "compId": "GLOBAL",
    "poomsaeStatus": "NR",
    "accommodationDetails": "",
    "specialRole": "None",
    "bankName": "MAYBANK",
    "phone": "0162451282",
    "bankAccount": "114767160683",
    "id": "GLOBAL_890117145439",
    "clubName": "KELAB TAEKWONDO MOI",
    "accommodation": "Yes",
    "hotelDaysProvided": 3,
    "carPlate": ""
  },
  {
    "clubName": "SKID TAEKWONDO CLUB",
    "bankName": "Hong Leong Bank",
    "poomsaeStatus": "TR",
    "specialRole": "None",
    "carPlate": "JTN9307",
    "residentialLocation": "Johor",
    "phone": "0143116485",
    "accommodation": "No",
    "bankAccount": "32351006452",
    "distance": 46,
    "password": "181089",
    "compId": "GLOBAL",
    "createdAt": "2026-07-23T08:03:02.601Z",
    "id": "GLOBAL_891018016679",
    "kyorugiStatus": "SR",
    "nric": "891018-01-6679",
    "fullName": "Vicknesh Chandrasekharan"
  },
  {
    "id": "GLOBAL_900202015213",
    "accommodation": "Yes",
    "hotelDaysProvided": 3,
    "specialRole": "None",
    "residentialLocation": "Sabah",
    "createdAt": "2026-07-20T13:32:33.376Z",
    "clubName": "MBV TKD CLUB",
    "poomsaeStatus": "NR",
    "accommodationMapsLink": "",
    "bankAccount": "101468255522",
    "bankName": "Maybank",
    "carPlate": "",
    "compId": "GLOBAL",
    "phone": "0109333569",
    "hotelCheckoutDate": "Monday",
    "fullName": "RAYMOND TOH MENG HUI",
    "kyorugiStatus": "NR",
    "nric": "900202015213",
    "distance": 6400,
    "password": "RAYmond90.",
    "accommodationDetails": ""
  },
  {
    "phone": "016-9774439",
    "specialRole": "None",
    "compId": "GLOBAL",
    "carPlate": "VP5977",
    "bankName": "MAYBANK BERHAD",
    "bankAccount": "112081054703",
    "clubName": "JOHOR KELAB TAEKWONDO HARMONY",
    "nric": "901129-10-6155",
    "kyorugiStatus": "SR",
    "fullName": "LIM YEN TENG",
    "poomsaeStatus": "TR",
    "residentialLocation": "JOHOR BAHRU, JOHOR",
    "id": "GLOBAL_901129106155",
    "distance": 60,
    "password": "yen.901129",
    "accommodation": "No",
    "createdAt": "2026-07-20T13:00:27.339Z"
  },
  {
    "bankName": "CIMB BANK",
    "clubName": "TLDM",
    "residentialLocation": "PUNCAK ALAM SELANGOR",
    "carPlate": "VQQ1124",
    "nric": "910624-14-6247",
    "id": "GLOBAL_910624146247",
    "kyorugiStatus": "NR",
    "phone": "0129114199",
    "poomsaeStatus": "NR",
    "createdAt": "2026-08-30T04:58:28.512Z",
    "compId": "GLOBAL",
    "distance": 160,
    "password": "Ejat@24691",
    "bankAccount": "7600615472",
    "specialRole": "None",
    "accommodation": "No",
    "fullName": "RIZZATDIN BIN SHAHRUDIN"
  },
  {
    "residentialLocation": "KL",
    "carPlate": "VQ 311",
    "id": "GLOBAL_910805086298",
    "bankName": "Affin",
    "createdAt": "2026-08-30T04:30:48.902Z",
    "kyorugiStatus": "SR",
    "clubName": "TLDM",
    "fullName": "'AMILA FAQHIRA ZAINODIN",
    "poomsaeStatus": "TR",
    "compId": "GLOBAL",
    "specialRole": "None",
    "nric": "910805-08-6298",
    "password": "123456",
    "distance": 42,
    "phone": "01119111770",
    "accommodation": "No",
    "bankAccount": "200480347730"
  },
  {
    "phone": "0188728347",
    "fullName": "Oo Yong Yung Fuei",
    "accommodation": "Yes",
    "id": "GLOBAL_920206145347",
    "hotelDaysProvided": 3,
    "distance": 650,
    "password": "YungFuei@92",
    "nric": "920206-14-5347",
    "accommodationMapsLink": "",
    "poomsaeStatus": "IR",
    "kyorugiStatus": "IR",
    "compId": "GLOBAL",
    "bankAccount": "112558195372",
    "accommodationDetails": "",
    "bankName": "MAYBANK",
    "createdAt": "2026-07-20T12:40:28.716Z",
    "clubName": "MBW",
    "residentialLocation": "Kuala Lumpur",
    "specialRole": "None",
    "hotelCheckoutDate": "Monday",
    "carPlate": "SMF 2826"
  },
  {
    "createdAt": "2026-07-23T13:35:52.765Z",
    "nric": "920617-01-6152",
    "compId": "GLOBAL",
    "password": "Che920617",
    "distance": 60,
    "accommodation": "No",
    "fullName": "CHE SHI MIN",
    "poomsaeStatus": "IR",
    "phone": "0167892667",
    "kyorugiStatus": "IR",
    "bankName": "Maybank",
    "id": "ACC_920617016152",
    "clubName": "Wenwu martial arts",
    "bankAccount": "101218301093",
    "carPlate": "DDK9991",
    "specialRole": "RIC",
    "residentialLocation": "Johor Bahru"
  },
  {
    "id": "GLOBAL_920727146193",
    "password": "Along44103!",
    "distance": 30,
    "nric": "920727146193",
    "createdAt": "2026-08-30T04:57:02.079Z",
    "kyorugiStatus": "SR",
    "fullName": "Mohd Na'im Afandi Bin Mohd Azami",
    "clubName": "Victory Taekwondo Club",
    "bankName": "Maybank",
    "residentialLocation": "Petaling Jaya",
    "specialRole": "None",
    "poomsaeStatus": "TR",
    "carPlate": "Ndm454",
    "compId": "GLOBAL",
    "bankAccount": "112018123829",
    "phone": "0147242694",
    "accommodation": "No"
  },
  {
    "compId": "GLOBAL",
    "password": "260393@Leen08",
    "distance": 9.5,
    "kyorugiStatus": "SR",
    "specialRole": "None",
    "bankAccount": "8881025016900",
    "fullName": "LEENA DEVI A/P CHANDRASEKHARAN",
    "id": "GLOBAL_930326015378",
    "nric": "930326015378",
    "carPlate": "UC9326",
    "bankName": "AMBANK",
    "accommodation": "No",
    "clubName": "SKID TAEKWONDO CLUB",
    "createdAt": "2026-07-23T06:44:13.275Z",
    "phone": "0167373224",
    "poomsaeStatus": "TR",
    "residentialLocation": "JOHOR BAHRU, JOHOR"
  },
  {
    "bankAccount": "162179655689",
    "carPlate": "AMA 5693",
    "nric": "930605-14-5570",
    "accommodation": "No",
    "clubName": "Hypermax Taekwondo Club",
    "id": "ACC_930605145570",
    "bankName": "Maybank",
    "poomsaeStatus": "TR",
    "specialRole": "None",
    "password": "Aslan5693@",
    "distance": 160,
    "phone": "0127105033",
    "kyorugiStatus": "SR",
    "fullName": "Shahrina Aqilah binti Shahrudin",
    "createdAt": "2026-08-30T13:26:13.522Z",
    "compId": "GLOBAL",
    "residentialLocation": "Puncak Alam"
  },
  {
    "phone": "0174674751",
    "specialRole": "None",
    "distance": 30,
    "password": "Tasnim215272$",
    "nric": "941110-02-5503",
    "bankAccount": "7631865976",
    "kyorugiStatus": "SR",
    "compId": "GLOBAL",
    "fullName": "BURHANUDDIN BIN KHOZEMA",
    "clubName": "MBW",
    "bankName": "CIMB",
    "carPlate": "PnU3498",
    "poomsaeStatus": "SR",
    "residentialLocation": "Setapak, Kuala Lumpur",
    "accommodation": "No",
    "createdAt": "2026-08-30T04:26:45.370Z",
    "id": "GLOBAL_941110025503"
  },
  {
    "specialRole": "None",
    "hotelCheckoutDate": "Monday",
    "nric": "950214105510",
    "phone": "0193216433",
    "createdAt": "2026-07-20T14:03:30.645Z",
    "kyorugiStatus": "SR",
    "accommodationMapsLink": "",
    "carPlate": "-",
    "clubName": "Speed Power Taekwondo KL",
    "compId": "GLOBAL",
    "bankAccount": "164810158077",
    "bankName": "Maybank",
    "fullName": "Nur Hazlyana binti Mohd Hanizul",
    "accommodation": "Yes",
    "hotelDaysProvided": 3,
    "accommodationDetails": "",
    "poomsaeStatus": "TR",
    "distance": 656,
    "password": ".taekwondo1",
    "residentialLocation": "Wangsa Maju, KL",
    "id": "GLOBAL_950214105510"
  },
  {
    "bankAccount": "162384974900",
    "id": "GLOBAL_950421146358",
    "fullName": "Lai Yen Theng",
    "nric": "950421-14-6358",
    "phone": "0169751140",
    "distance": 16,
    "password": "Wallace$77",
    "specialRole": "None",
    "kyorugiStatus": "NR",
    "poomsaeStatus": "SR",
    "compId": "GLOBAL",
    "createdAt": "2026-08-30T04:40:30.939Z",
    "residentialLocation": "Cheras, Selangor",
    "bankName": "Maybank",
    "accommodation": "No",
    "clubName": "TEMATA",
    "carPlate": "ANE954"
  },
  {
    "accommodation": "Yes",
    "bankName": "Mybank",
    "specialRole": "None",
    "id": "GLOBAL_950630035638",
    "clubName": "One Force Tkd Club",
    "accommodationDetails": "",
    "carPlate": "",
    "phone": "01115028848",
    "poomsaeStatus": "SR",
    "createdAt": "2026-07-23T04:31:41.127Z",
    "bankAccount": "153011174481",
    "hotelCheckoutDate": "Monday",
    "nric": "950630035638",
    "compId": "GLOBAL",
    "accommodationMapsLink": "",
    "password": "Zainab95@",
    "distance": 350,
    "kyorugiStatus": "NR",
    "hotelDaysProvided": 3,
    "residentialLocation": "Kelantan",
    "fullName": "Zainab Binti Musa"
  },
  {
    "accommodation": "Yes",
    "fullName": "NOR MASHITAH BINTI MOHD NAZAR",
    "bankAccount": "14238020082431",
    "accommodationDetails": "",
    "hotelCheckoutDate": "Monday",
    "id": "GLOBAL_950705146640",
    "nric": "950705146640",
    "password": "Gentagit5795",
    "distance": 723,
    "poomsaeStatus": "SR",
    "specialRole": "None",
    "compId": "GLOBAL",
    "hotelDaysProvided": 3,
    "residentialLocation": "RAWANG, SELANGOR",
    "createdAt": "2026-07-20T12:37:46.545Z",
    "accommodationMapsLink": "",
    "kyorugiStatus": "SR",
    "phone": "0133827115",
    "carPlate": "",
    "bankName": "BANK ISLAM",
    "clubName": "HYPERMAX"
  },
  {
    "accommodationMapsLink": "",
    "bankAccount": "551593540815",
    "accommodationDetails": "",
    "specialRole": "None",
    "carPlate": "",
    "compId": "GLOBAL",
    "residentialLocation": "IPOH PERAK",
    "phone": "0175102343",
    "hotelDaysProvided": 3,
    "clubName": "WUKWON JOHOR",
    "id": "GLOBAL_960727086422",
    "bankName": "MAYBANK",
    "kyorugiStatus": "NR",
    "poomsaeStatus": "SR",
    "fullName": "NURSAKINAH BINTI ARIFFIN",
    "nric": "960727086422",
    "accommodation": "Yes",
    "hotelCheckoutDate": "Monday",
    "password": "Blueskyna27",
    "distance": 450,
    "createdAt": "2026-07-21T10:57:25.016Z"
  },
  {
    "clubName": "KORYO TAEKWONDO CLUB",
    "bankName": "MAYBANK",
    "residentialLocation": "ELMINA SELANGOR",
    "carPlate": "PPC5785",
    "kyorugiStatus": "SR",
    "compId": "GLOBAL",
    "phone": "0176185649",
    "id": "GLOBAL_961020106092",
    "createdAt": "2026-08-30T04:49:29.661Z",
    "bankAccount": "162085672034",
    "accommodation": "No",
    "distance": 120,
    "password": "NYn1sa96.",
    "nric": "961020106092",
    "poomsaeStatus": "SR",
    "fullName": "NOOR YUANNISA",
    "specialRole": "None"
  },
  {
    "nric": "961229065041",
    "hotelCheckoutDate": "Monday",
    "poomsaeStatus": "SR",
    "compId": "GLOBAL",
    "accommodationDetails": "",
    "password": "961229",
    "distance": 765,
    "accommodationMapsLink": "",
    "id": "GLOBAL_961229065041",
    "accommodation": "Yes",
    "fullName": "LEE CHENG YI",
    "bankName": "Maybank",
    "createdAt": "2026-07-20T13:24:42.511Z",
    "residentialLocation": "Kepong, Kuala Lumpur",
    "clubName": "TEMERLOH EDUCATIONAL TAEKWONDO CLUB",
    "hotelDaysProvided": 3,
    "bankAccount": "156020359968",
    "carPlate": "VGS6229",
    "specialRole": "None",
    "kyorugiStatus": "IR",
    "phone": "0169867953"
  },
  {
    "id": "GLOBAL_980512107263",
    "fullName": "SYED MOHAMMAD DARWISY SYED INDERA",
    "distance": 42,
    "password": "birth9805",
    "kyorugiStatus": "SR",
    "poomsaeStatus": "TR",
    "specialRole": "None",
    "phone": "01135135530",
    "carPlate": "JUG9429",
    "createdAt": "2026-08-30T04:31:33.372Z",
    "accommodation": "No",
    "nric": "980512-10-7263",
    "residentialLocation": "Kajang",
    "clubName": "MTR",
    "bankAccount": "162414205911",
    "compId": "GLOBAL",
    "bankName": "MAYBANK"
  }
];
